#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/../.."

app_origin="${1:-http://localhost:3000}"
key_name="lapikud-app"

# load .env file in
if [[ -f .env ]]; then
  set -a
  source .env
  set +a
fi
bucket="${GARAGE_PHOTO_BUCKET:-lapikud-photos}"

# run the garage cli inside the container
garage() {
  docker compose exec -T garage /garage -c /etc/garage.toml "$@" 2>/dev/null
}

# create garage.toml with a fresh secret if missing
if [[ -f garage.toml ]]; then
  echo "config: garage.toml exists"
else
  sed "s/generated by pnpm garage:setup/$(openssl rand -hex 32)/" garage.example.toml > garage.toml
  echo "config: wrote garage.toml with a new rpc secret"
fi

# start garage and wait until healthy
docker compose up -d --wait garage > /dev/null
echo "garage: running"

# give new nodes a role so the cluster accepts data
unassigned=$(garage status | awk '/NO ROLE ASSIGNED/ { print $1 }')
if [[ -z "$unassigned" ]]; then
  echo "layout: already assigned"
else
  for node in $unassigned; do
    garage layout assign -z dc1 -c 1G "$node" > /dev/null
  done
  version=$(garage layout show | sed -n 's/.*Current cluster layout version: \([0-9]*\).*/\1/p')
  garage layout apply --version $((${version:-0} + 1)) > /dev/null
  echo "layout: assigned"
fi

# create the app key
if garage key list | grep -q "$key_name"; then
  echo "key: \"$key_name\" exists"
else
  created=$(garage key create "$key_name")
  echo "key: created \"$key_name\". Put these in .env:"
  echo "GARAGE_ACCESS_KEY=$(awk '/Key ID/ { print $NF }' <<< "$created")"
  echo "GARAGE_SECRET_KEY=$(awk '/Secret key/ { print $NF }' <<< "$created")"
fi

# create the photos bucket and let the app key use it
garage bucket list | grep -q "$bucket" || garage bucket create "$bucket" > /dev/null
garage bucket allow --read --write --owner "$bucket" --key "$key_name" > /dev/null
echo "bucket: \"$bucket\" ready for \"$key_name\""

# cors needs the key from .env
if [[ -z "${GARAGE_ENDPOINT:-}" || -z "${GARAGE_ACCESS_KEY:-}" || -z "${GARAGE_SECRET_KEY:-}" ]]; then
  echo "cors: skipped; put the key in .env and run this again"
  exit 0
fi

# load in cors. Replace APP_ORIGIN with environment app origin
cors=$(sed "s|APP_ORIGIN|$app_origin|" scripts/garage/cors.xml)
# let the browser upload photos straight to the bucket
curl --fail --silent --show-error --request PUT "${GARAGE_ENDPOINT%/}/$bucket?cors" \
  --aws-sigv4 "aws:amz:${GARAGE_REGION:-garage}:s3" \
  --user "$GARAGE_ACCESS_KEY:$GARAGE_SECRET_KEY" \
  --header "Content-Type: application/xml" \
  --header "Content-MD5: $(printf '%s' "$cors" | openssl dgst -md5 -binary | openssl base64)" \
  --data-binary "$cors"
echo "cors: uploads allowed from $app_origin"
